window.SWIM_POOLS = [
  {
    id: "jamsil-indoor",
    name: "Jamsil Complex Swimming Pool",
    district: "Songpa-gu",
    address: "25 Olympic-ro, Songpa-gu, Seoul",
    lat: 37.5147,
    lng: 127.0731,
    tags: ["public", "indoor"],
    hours: "Hours vary by program. Check before visiting.",
    price: "Adults 5,000-8,000 KRW",
    note: "Convenient public indoor pool with good transit access.",
    source: "Check Seoul city sports facility listings"
  },
  {
    id: "olympic-park",
    name: "Olympic Swimming Pool",
    district: "Songpa-gu",
    address: "424 Olympic-ro, Songpa-gu, Seoul",
    lat: 37.5205,
    lng: 127.1226,
    tags: ["public", "indoor"],
    hours: "Class and free-swim schedule may differ.",
    price: "Free swim 6,000-9,000 KRW",
    note: "Large facility with solid basics. Check weekend class hours.",
    source: "Check KSPO / Olympic Park facility info"
  },
  {
    id: "mapo-art",
    name: "Mapo Art Center Pool",
    district: "Mapo-gu",
    address: "28 Daehung-ro 20-gil, Mapo-gu, Seoul",
    lat: 37.5498,
    lng: 126.9455,
    tags: ["public", "indoor"],
    hours: "Verify weekday / weekend free-swim times.",
    price: "Adults 5,000-7,000 KRW",
    note: "Easy to combine with nearby cultural facilities. Check class times.",
    source: "Check Mapo Art Center operating info"
  },
  {
    id: "seodaemun",
    name: "Seodaemun Culture & Sports Center Pool",
    district: "Seodaemun-gu",
    address: "39 Baekryeon-gil, Seodaemun-gu, Seoul",
    lat: 37.5862,
    lng: 126.9461,
    tags: ["public", "indoor"],
    hours: "Check weekday class / free-swim times.",
    price: "Adults 5,000-7,000 KRW",
    note: "Good place to check beginner class options.",
    source: "Check Seodaemun-gu facility listings"
  },
  {
    id: "mokdong",
    name: "Mokdong Sports Complex Indoor Pool",
    district: "Yangcheon-gu",
    address: "939 Anyangcheon-ro, Yangcheon-gu, Seoul",
    lat: 37.5304,
    lng: 126.8816,
    tags: ["public", "indoor"],
    hours: "Operating schedule depends on classes and free-swim blocks.",
    price: "Adults 5,000-8,000 KRW",
    note: "Large southwest Seoul sports facility. Check event schedules too.",
    source: "Check Yangcheon-gu sports facility info"
  },
  {
    id: "worldcup",
    name: "Seoul World Cup Stadium Pool",
    district: "Mapo-gu",
    address: "240 World Cup-ro, Mapo-gu, Seoul",
    lat: 37.5683,
    lng: 126.8973,
    tags: ["public", "indoor"],
    hours: "Class-focused operation. Verify free-swim hours separately.",
    price: "Adults 5,000-8,000 KRW",
    note: "Near the stadium and easy to pair with other sports facilities.",
    source: "Check Seoul facility listings"
  },
  {
    id: "ttukseom",
    name: "Ttukseom Hangang Pool",
    district: "Gwangjin-gu",
    address: "112 Jayang-dong, Gwangjin-gu, Seoul",
    lat: 37.5297,
    lng: 127.0668,
    tags: ["public", "hangang"],
    hours: "Open in summer. Usually 09:00-18:00.",
    price: "Adults around 5,000 KRW, discounts for children",
    note: "One of the most accessible Hangang pools, with heavy foot traffic.",
    source: "Check Hangang pool operation notices"
  },
  {
    id: "yeouido",
    name: "Yeouido Hangang Pool",
    district: "Yeongdeungpo-gu",
    address: "82-9 Yeouido-dong, Yeongdeungpo-gu, Seoul",
    lat: 37.5293,
    lng: 126.9345,
    tags: ["public", "hangang"],
    hours: "Open in summer. Usually 09:00-18:00.",
    price: "Adults around 5,000 KRW, discounts for children",
    note: "Easy city access and a nice riverfront view.",
    source: "Check Hangang pool operation notices"
  },
  {
    id: "jamwon",
    name: "Jamwon Hangang Pool",
    district: "Seocho-gu",
    address: "121 Jamwon-dong, Seocho-gu, Seoul",
    lat: 37.5207,
    lng: 127.0127,
    tags: ["public", "hangang"],
    hours: "Open in summer. Usually 09:00-18:00.",
    price: "Adults around 5,000 KRW, discounts for children",
    note: "Good option on the Gangnam side. Check peak-hour crowding.",
    source: "Check Hangang pool operation notices"
  },
  {
    id: "mangwon",
    name: "Mangwon Hangang Pool",
    district: "Mapo-gu",
    address: "312-6 Mangwon-dong, Mapo-gu, Seoul",
    lat: 37.5551,
    lng: 126.8959,
    tags: ["public", "hangang"],
    hours: "Open in summer. Usually 09:00-18:00.",
    price: "Adults around 5,000 KRW, discounts for children",
    note: "Popular for families. Check parking and shade availability.",
    source: "Check Hangang pool operation notices"
  },
  {
    id: "nanji",
    name: "Nanji Hangang Water Park",
    district: "Mapo-gu",
    address: "162 Hangangnanji-ro, Mapo-gu, Seoul",
    lat: 37.5689,
    lng: 126.8762,
    tags: ["public", "hangang"],
    hours: "Open in summer. Usually 09:00-18:00.",
    price: "Adults around 3,000 KRW, discounts for children",
    note: "More of a water play area than a full swimming pool.",
    source: "Check Hangang water park notices"
  },
  {
    id: "jungnang",
    name: "Jungnang Culture & Sports Center Pool",
    district: "Jungnang-gu",
    address: "47 Sindaero 72-gil, Jungnang-gu, Seoul",
    lat: 37.5847,
    lng: 127.0954,
    tags: ["public", "indoor"],
    hours: "Check weekday class / free-swim times.",
    price: "Adults 5,000-7,000 KRW",
    note: "Local sports facility with class schedules worth checking first.",
    source: "Check Jungnang-gu facility listings"
  }
];
